### ISSUE TITLE
add a Readme 

### ISSUE THREAD

**Issue by lduboeuf** [ubports/ubuntu-app-launch#13]
For newcomers, provide a quick Readme file to answer:
- What is the purpose of this repository ?
- How can i test / run ?
- How can i contribute ?
- How can i build and hack ?

**Comment by lduboeuf** [comment]
Oh found the doc folder. So maybe a link is a good starter

**Comment by UniversalSuperBox** [comment]
ubuntu-app-launch has been renamed to lomiri-app-launch and moved to https://gitlab.com/ubports/core/lomiri-app-launch. Unfortunately, I don't think this issue has been solved yet. Please let us know by creating a new issue on the new repository. Thank you!
