### ISSUE TITLE
Provide a fallback icon path

### ISSUE THREAD

**Issue by lduboeuf** [ubports/ubuntu-app-launch#14]
From discussion : https://github.com/ubports/unity8/pull/216

We need to provide a default icon when anything went wrong when loading app icon. Seems to be here for implementing it: https://github.com/ubports/ubuntu-app-launch/blob/xenial/libubuntu-app-launch/application-icon-finder.cpp#L73

**Comment by UniversalSuperBox** [comment]
ubuntu-app-launch has been renamed to lomiri-app-launch and moved to https://gitlab.com/ubports/core/lomiri-app-launch. Unfortunately, I don't think this issue has been solved yet. Please let us know by creating a new issue on the new repository. Thank you!
