### ISSUE TITLE
Missing properties-cpp dependency

### ISSUE THREAD

**Issue by vanyasem** [ubports/ubuntu-app-launch#2]
This package depends on `properties-cpp`, but cmake doesn't check for it's existence

**Comment by vanyasem** [comment]
https://launchpad.net/properties-cpp

**Comment by UniversalSuperBox** [comment]
ubuntu-app-launch has been renamed to lomiri-app-launch and moved to https://gitlab.com/ubports/core/lomiri-app-launch. It is possible that this issue was fixed in the transition. If not, please let us know by creating a new issue on the new repository. Thank you!
