### ISSUE TITLE
Inherited bug from cmake-extras

### ISSUE THREAD

**Issue by vanyasem** [ubports/ubuntu-app-launch#4]
This package [fails to compile](https://paste.ubuntu.com/p/v3PJSx8GnV/) due to this bug: https://github.com/ubports/cmake-extras/issues/2

Patching cmake-extras breaks the package and requires replacing `GTEST_MAIN_LIBRARIES` with `GMOCK_LIBRARIES` in `tests/CMakeLists.txt`

**Comment by dpniel** [comment]
@vanyasem fancy creating a PR for this?

**Comment by vanyasem** [comment]
@dpniel I should make a PR for cmake-extras first ;)

The [patch](https://github.com/vanyasem/Unity8-Arch/commit/538d9d7d29c2e94d97702d8618caa2af4b8cd1a4#diff-efa0bd33929dd7efc772a4780cd9ba4e) is ready, I just need some more time to test it

**Comment by UniversalSuperBox** [comment]
ubuntu-app-launch has been renamed to lomiri-app-launch and moved to https://gitlab.com/ubports/core/lomiri-app-launch. It is possible that this issue was fixed in the transition. If not, please let us know by creating a new issue on the new repository. Thank you!
