### ISSUE TITLE
no auto completion

### ISSUE THREAD

**Issue by doniks** [ubports/ubuntu-app-launch#5]
sometimes it is helpful to start an app from terminal. (e.g. right now the libertine scope has issues and doesn't show icons)

it is possible to start from terminal, but it is a bit cumbersome, because of the non-intuitive appids

with the below completion script, one has autocompletion of app ids. 

``/usr/share/bash-completion/completions/ubuntu-app-launch``

```
# -*- shell-script -*-

function _ubuntu-app-launch()
{
    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=( $(compgen -W "$(ubuntu-app-launch-appids)" -- ${cur} ) )
} && complete -F _ubuntu-app-launch ubuntu-app-launch
```

It works if I copy it directly onto my device, but I don't really know where to stick it into the source code to have it packaged and installed.

**Comment by NeoTheThird** [comment]
Doesn't this have to go into bash-completion? Where do the other scripts of this kind come from?

**Comment by doniks** [comment]
libertine contains it's own

phablet@ubuntu-phablet:/usr/share/bash-completion/completions$ dpkg --listfiles libertine-tools 
/.
/usr
/usr/bin
/usr/bin/libertine-shell
/usr/bin/libertine-container-manager
/usr/share
/usr/share/bash-completion
/usr/share/bash-completion/completions
/usr/share/bash-completion/completions/libertine-shell
/usr/share/bash-completion/completions/libertine-container-manager
/usr/share/man/man1/libertine-container-manager.1.gz
/usr/share/man/man1/libertine-shell.1.gz
/usr/share/doc
/usr/share/doc/libertine-tools
/usr/share/doc/libertine-tools/changelog.gz
/usr/share/doc/libertine-tools/copyright

**Comment by NeoTheThird** [comment]
Ok, would you be interested in investigating this further? Maybe check out the [libertine](github.com/ubports/libertine) repo and see where the file is coming from, and then try to implement the same thing here?

**Comment by doniks** [comment]
closed via https://github.com/ubports/ubuntu-app-launch/pull/6
