### ISSUE TITLE
Hard dependency on libertine and xmir

### ISSUE THREAD

**Issue by dobey** [ubports/ubuntu-app-launch#9]
Currently there is a hard dependency on libertine and xmir, and libertine only supports creating an Ubuntu chroot on an Ubuntu system that is of the same release. This means anyone porting the Unity 8 stack to other distributions, must also build and ship libertine, even though it will not work.

Making libertine generic and usable on any distribution, and also support containers of those distributions, would be an extremely large amount of work. We should instead make libertine an optional dependency, so that we can still ship it on Ubuntu builds, but others can avoid it. As Xmir will eventually be replaced by Xwayland, this would also be a step toward supporting that.

**Comment by UniversalSuperBox** [comment]
ubuntu-app-launch has been renamed to lomiri-app-launch and moved to https://gitlab.com/ubports/core/lomiri-app-launch. Unfortunately, I don't think this issue has been solved yet. Please let us know by creating a new issue on the new repository. Thank you!
